name: CI build

on:
  workflow_call:
    inputs:
      javaVersion:
        required: true
        type: number
      ACTIONFILE:
        required: true
        type: string
    
    secrets:
      Dockerhub_username:
        required: true
      Dockerhub_token:
        required: true

env:
  ACTIONFILE: ${{ inputs.ACTIONFILE }}

jobs:
  CI_Build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '${{ inputs.javaVersion }}'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn -DskipTests clean package
  Docker_Build:
    runs-on: ubuntu-latest
    needs: [CI_Build]
    steps:
      - uses: actions/checkout@v3
      
      - name: Get properties
        id: app_name
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: ${{ env.ACTIONFILE }}
          prop_path: application_properties.APPNAME

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.Dockerhub_username }}
          password: ${{ secrets.Dockerhub_token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: sandeep4642/${{ steps.app_name.outputs.prop}}:${{github.run_number}}